language: php

php:
  - 7.3
  - 7.4

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - travis_retry composer install --prefer-dist

script:
  - make test
