version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    hostname: mitra-backend-postgresql
    container_name: mitra-backend-postgresql
    environment:
      POSTGRES_USER: mitra
      POSTGRES_PASSWORD: mitra
    ports:
      - 5432:5432
  php:
    build:
      context: ./docker/php
      dockerfile: dev/Dockerfile
      args:
        HOST_USER_ID: ${USER_ID}
    hostname: mitra-backend-php
    container_name: mitra-backend-php
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_PORT: 1337
      DATABASE_URL: postgres://mitra:mitra@postgresql:5432/mitra
      DATABASE_URL_TEST: postgres://mitra:mitra@postgresql:5432/mitra-test
      JWT_SECRET: s3kr3T!
      BASE_URL: 'http://localhost:1337'
      INSTANCE_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5eSBLpSLW4YgR7pN5T7U
        g41LkVOCq8Vi9HHpH/4G46rSGyi7Y4jQ3nPdu8A3t7QUT6hpi4UIXkK/BsrHo6No
        DPeOxKASk+6MdY2+rf09nT8ErRvaGSmwuToa2J6CcI+WPukgGNYeyR6Evm9IiavA
        SiTvlPndeNPxkDQhvh3uWRZnkhfTMFdFh3gSbTo2eFspj58bWrfDsE3ujKC3m3nk
        LByg20rojoJBpGffBUuyIn141Qy9wiUIUaCPFIvVgEMsrcUK0Yf5EVzkew4xH4eZ
        3Dg3edhVu2lqo7YIWYQFgst03bRNNGZ7DIQ1XxRv7TxlD/kE+LVAdiEzGDYQps4o
        cQIDAQAB
        -----END PUBLIC KEY-----

      INSTANCE_PRIVATE_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDl5IEulItbhiBH
        uk3lPtSDjUuRU4KrxWL0cekf/gbjqtIbKLtjiNDec927wDe3tBRPqGmLhQheQr8G
        ysejo2gM947EoBKT7ox1jb6t/T2dPwStG9oZKbC5OhrYnoJwj5Y+6SAY1h7JHoS+
        b0iJq8BKJO+U+d140/GQNCG+He5ZFmeSF9MwV0WHeBJtOjZ4WymPnxtat8OwTe6M
        oLebeeQsHKDbSuiOgkGkZ98FS7IifXjVDL3CJQhRoI8Ui9WAQyytxQrRh/kRXOR7
        DjEfh5ncODd52FW7aWqjtghZhAWCy3TdtE00ZnsMhDVfFG/tPGUP+QT4tUB2ITMY
        NhCmzihxAgMBAAECggEAewiZ4lX5ZxgXOowImEHR9j2uTa6F5mwTE4PLIiYPhdSr
        8YERGKnmLsePyaWLrDMiE6esJNEjs17BYV8xDPCtBROQQsbwal9mqJsdi3xWd0t8
        szCOvpzDSb5BE+FxKdCOtkiJtwERJM3CeTCRf6x9krDFz9MRplK3m1drH5ZhMyd4
        x33ryWYP6LH5sE1pqS9/GLVpJubSN5YG+GHxl0skSE+50HjOMkiwz6syu2dWgn7v
        +ka5TaJHrV/s1Bcil9xG/FoanCFtoSYVGWK9l8rDusVtm+dvOHKM6h2PnnNI9tfp
        hmGJLzwCMMy2QlJGuslkQEAUyyycY5bR/CyYm+NhSQKBgQDzChwDRx7HeXQ3v9tj
        JFsSwmZR+jY94Psf/+M632WKwtuPC7AUkFmp6Sq8xjY3+OZZnbQTxv40n97MNSVD
        USjWsVnG4SDWNHRlZ2ZZFrpHC9ZMTUblHyPgVQyIGCufSwJSw52h/GbGwXU4dzNZ
        7bieqpWiMvNSSRsLJfEGUMCiJwKBgQDyJusaYP73x42B/n8WMiPLAkQlCKDA7XdI
        Tma7tvrDOCW94yWH19y/5tPWa+m2wj4aBnBb8Gkp+CZhuYyQWh2v6vs8TYG8JjST
        7RqxBoHxxZYaSShMilUt1y0o35AyLRgAfu+18UOlbUTcPj/+GAm7BuyNiNw5WkSj
        KIorXgI3pwKBgQCVaaejFDwF4dLi2x4iqx0aQUzqJOrny8JW/9dQQDqKvhSAsmzD
        l6Kn5GKTvz9h1bC3c05bwkBRVd+Ap0OLSP/UTR+mNo0bYxATryeqqWBHgS1zpyZo
        gWZq6Z5UpJdczJ5XB0+HYEZG9nP8DLwTEyQm1zQ6jRwtgCgSCHdOrKJgjQKBgGTM
        4Jc1g01/qx9O4nZJ3u51/gnwgoJtF3do84j2jYJQUB2wfYID0KetnccnWr2yNAm/
        XmxXMl+/JbMOez3n1W3SgkzC8ttwh/h//dltHRCYsHg2tejOuNCBPxJBphPNA63J
        KV3ylbc6Oiz4WMkcFojdRAFS1GGneuT0TjfpRUEHAoGAUrziP8/0OG+iMGztBqqR
        OASuU0ph+eTooLukP2mjre/mHSR4/k4F97yRsMiR0lC1zn9a4dAvIlULRNkhh5yj
        8+m1Wjsdrj07n2usnVBvcH48DKwtYvdR2lCvh+RRu7+L33qIC39VvgmLkseCn6/g
        RnGILYgxVo3dz1UpMP0J05k=
        -----END PRIVATE KEY-----

    ports:
      - 1337:1337
    volumes:
      - ./:/var/www/html
      - ~/.bash_aliases:/home/www-data/.bash_aliases:rw
      - ~/.bash_history:/home/www-data/.bash_history:rw
      - ~/.gitconfig:/home/www-data/.gitconfig:rw
    secrets:
      - ssh_host_key
  composer:
    build:
      context: ./docker
      dockerfile: composer/Dockerfile
      args:
        HOST_USER: ${USER}
        HOST_USER_ID: ${USER_ID}
    hostname: mitra-backend-composer
    container_name: mitra-backend-composer
    volumes:
      - ./:/app
secrets:
  ssh_host_key:
    file: ~/.ssh/id_rsa
