version: '3.7'

services:
  mariadb:
    image: mariadb:10
    hostname: mitra-backend-mariadb
    container_name: mitra-backend-mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        HOST_USER: ${USER}
        HOST_USER_ID: ${USER_ID}
    hostname: mitra-backend-php
    container_name: mitra-backend-php
    environment:
      APP_ENV: dev
      APP_PORT: 1337
    ports:
      - 1337:1337
    volumes:
      - ../:/var/www/html
      - ~/.bash_aliases:/home/www-data/.bash_aliases:rw
      - ~/.bash_history:/home/www-data/.bash_history:rw
      - ~/.gitconfig:/home/www-data/.gitconfig:rw
    secrets:
      - ssh_host_key
  composer:
    build:
      context: ./
      dockerfile: composer/Dockerfile
      args:
        HOST_USER: ${USER}
        HOST_USER_ID: ${USER_ID}
    volumes:
      - ../:/app
secrets:
  ssh_host_key:
    file: ~/.ssh/id_rsa