version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    hostname: mitra-backend-postgresql
    container_name: mitra-backend-postgresql
    environment:
      POSTGRES_USER: mitra
      POSTGRES_PASSWORD: mitra
    ports:
      - 5432:5432
  php:
    build:
      context: ./php
      dockerfile: dev/Dockerfile
      args:
        HOST_USER_ID: ${USER_ID}
    hostname: mitra-backend-php
    container_name: mitra-backend-php
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_PORT: 1337
      DATABASE_URL: postgres://mitra:mitra@postgresql:5432/mitra
      JWT_SECRET: s3kr3T!
    ports:
      - 1337:1337
    volumes:
      - ../:/var/www/html
      - ~/.bash_aliases:/home/www-data/.bash_aliases:rw
      - ~/.bash_history:/home/www-data/.bash_history:rw
      - ~/.gitconfig:/home/www-data/.gitconfig:rw
    secrets:
      - ssh_host_key
  composer:
    build:
      context: ./
      dockerfile: composer/Dockerfile
      args:
        HOST_USER: ${USER}
        HOST_USER_ID: ${USER_ID}
    hostname: mitra-backend-composer
    container_name: mitra-backend-composer
    volumes:
      - ../:/app
secrets:
  ssh_host_key:
    file: ~/.ssh/id_rsa